// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: factory_reset.sql

package database

import (
	"context"
)

const factoryResetDatabase = `-- name: FactoryResetDatabase :exec
TRUNCATE user_progress, sessions, content_items, modules, courses, profiles RESTART IDENTITY CASCADE
`

// Reset the database to its initial state, RESTART IDENTITY CASCADE, means that the primary keys will be reset and any
// incrementing columns will be reset to 1.
func (q *Queries) FactoryResetDatabase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, factoryResetDatabase)
	return err
}
