// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: factory_reset.sql

package database

import (
	"context"
)

const factoryResetDatabase = `-- name: FactoryResetDatabase :exec

DELETE FROM user_progress
`

// Clear all data from tables in the correct order (respecting foreign keys)
// Start with dependent tables first, then parent tables
// Clear user progress (depends on profiles and content_items)
func (q *Queries) FactoryResetDatabase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, factoryResetDatabase)
	return err
}
