// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type ContentItem struct {
	ID           uuid.UUID
	ModuleID     uuid.UUID
	Title        string
	Description  sql.NullString
	RelativePath string
	ContentType  string
	Duration     sql.NullInt32
	Size         sql.NullInt64
	Order        int32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Course struct {
	ID           uuid.UUID
	Title        string
	Description  sql.NullString
	CreatorID    uuid.NullUUID
	RelativePath string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Module struct {
	ID           uuid.UUID
	CourseID     uuid.UUID
	Title        string
	Description  sql.NullString
	RelativePath string
	Order        int32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Profile struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserProgress struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ContentItemID uuid.UUID
	Completed     bool
	ProgressPct   float32
	LastPosition  sql.NullInt32
	LastAccessed  sql.NullTime
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}
