// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addExperienceToProfile = `-- name: AddExperienceToProfile :one
UPDATE profiles
SET experience = experience + $2,
    level      = (experience + $2) / 100 + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, name, created_at, updated_at, experience, gems, level, streak, last_active_date
`

type AddExperienceToProfileParams struct {
	ID         uuid.UUID
	Experience int32
}

func (q *Queries) AddExperienceToProfile(ctx context.Context, arg AddExperienceToProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, addExperienceToProfile, arg.ID, arg.Experience)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Experience,
		&i.Gems,
		&i.Level,
		&i.Streak,
		&i.LastActiveDate,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (id, created_at, updated_at, name)
VALUES ($1,
        now(),
        now(),
        $2)
RETURNING id, name, created_at, updated_at, experience, gems, level, streak, last_active_date
`

type CreateProfileParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile, arg.ID, arg.Name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Experience,
		&i.Gems,
		&i.Level,
		&i.Streak,
		&i.LastActiveDate,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE
FROM profiles
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, id)
	return err
}

const getAllProfiles = `-- name: GetAllProfiles :many
SELECT id, name, created_at, updated_at, experience, gems, level, streak, last_active_date
FROM profiles
`

func (q *Queries) GetAllProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, getAllProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Experience,
			&i.Gems,
			&i.Level,
			&i.Streak,
			&i.LastActiveDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileById = `-- name: GetProfileById :one
SELECT id, name, created_at, updated_at, experience, gems, level, streak, last_active_date
FROM profiles
WHERE id = $1
`

func (q *Queries) GetProfileById(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileById, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Experience,
		&i.Gems,
		&i.Level,
		&i.Streak,
		&i.LastActiveDate,
	)
	return i, err
}

const getProfileByName = `-- name: GetProfileByName :one
SELECT id, name, created_at, updated_at, experience, gems, level, streak, last_active_date
FROM profiles
WHERE name = $1
`

func (q *Queries) GetProfileByName(ctx context.Context, name string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByName, name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Experience,
		&i.Gems,
		&i.Level,
		&i.Streak,
		&i.LastActiveDate,
	)
	return i, err
}

const getProfileWithStats = `-- name: GetProfileWithStats :one
SELECT p.id, p.name, p.created_at, p.updated_at, p.experience, p.gems, p.level, p.streak, p.last_active_date,
       (p.experience % 100)         as xp_in_level,
       (100 - (p.experience % 100)) as xp_to_next_level
FROM profiles p
WHERE p.id = $1
`

type GetProfileWithStatsRow struct {
	ID             uuid.UUID
	Name           string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Experience     int32
	Gems           int32
	Level          int32
	Streak         int32
	LastActiveDate sql.NullTime
	XpInLevel      int32
	XpToNextLevel  int32
}

func (q *Queries) GetProfileWithStats(ctx context.Context, id uuid.UUID) (GetProfileWithStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileWithStats, id)
	var i GetProfileWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Experience,
		&i.Gems,
		&i.Level,
		&i.Streak,
		&i.LastActiveDate,
		&i.XpInLevel,
		&i.XpToNextLevel,
	)
	return i, err
}

const getProfilesByNamePattern = `-- name: GetProfilesByNamePattern :many
SELECT id, name, created_at, updated_at, experience, gems, level, streak, last_active_date
FROM profiles
WHERE name LIKE $1
`

func (q *Queries) GetProfilesByNamePattern(ctx context.Context, name string) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, getProfilesByNamePattern, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Experience,
			&i.Gems,
			&i.Level,
			&i.Streak,
			&i.LastActiveDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfilesCount = `-- name: GetProfilesCount :one
SELECT COUNT(*)
FROM profiles
`

func (q *Queries) GetProfilesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProfilesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateProfileByID = `-- name: UpdateProfileByID :one
UPDATE profiles
SET name       = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, created_at, updated_at, experience, gems, level, streak, last_active_date
`

type UpdateProfileByIDParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateProfileByID(ctx context.Context, arg UpdateProfileByIDParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfileByID, arg.ID, arg.Name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Experience,
		&i.Gems,
		&i.Level,
		&i.Streak,
		&i.LastActiveDate,
	)
	return i, err
}

const updateProfileGamification = `-- name: UpdateProfileGamification :one
UPDATE profiles
SET experience       = $2,
    gems             = $3,
    level            = $4,
    last_active_date = $5,
    streak           = $6,
    updated_at       = now()
WHERE id = $1
RETURNING id, name, created_at, updated_at, experience, gems, level, streak, last_active_date
`

type UpdateProfileGamificationParams struct {
	ID             uuid.UUID
	Experience     int32
	Gems           int32
	Level          int32
	LastActiveDate sql.NullTime
	Streak         int32
}

func (q *Queries) UpdateProfileGamification(ctx context.Context, arg UpdateProfileGamificationParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfileGamification,
		arg.ID,
		arg.Experience,
		arg.Gems,
		arg.Level,
		arg.LastActiveDate,
		arg.Streak,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Experience,
		&i.Gems,
		&i.Level,
		&i.Streak,
		&i.LastActiveDate,
	)
	return i, err
}

const updateProfileStreak = `-- name: UpdateProfileStreak :one
UPDATE profiles
SET streak           = $2,
    last_active_date = $3,
    updated_at       = now()
WHERE id = $1
RETURNING id, name, created_at, updated_at, experience, gems, level, streak, last_active_date
`

type UpdateProfileStreakParams struct {
	ID             uuid.UUID
	Streak         int32
	LastActiveDate sql.NullTime
}

func (q *Queries) UpdateProfileStreak(ctx context.Context, arg UpdateProfileStreakParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfileStreak, arg.ID, arg.Streak, arg.LastActiveDate)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Experience,
		&i.Gems,
		&i.Level,
		&i.Streak,
		&i.LastActiveDate,
	)
	return i, err
}
